server {
	listen 443 ssl;
	server_name mythofame.odex.dev;

	ssl_certificate /etc/letsencrypt/live/mythofame.odex.dev/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/mythofame.odex.dev/privkey.pem;
	ssl_trusted_certificate /etc/letsencrypt/live/mythofame.odex.dev/chain.pem;
		
	root /usr/share/nginx/html/mythofame;

	location / {
		try_files $uri $uri/ /index.html;
	}
}
